# -*- coding: utf-8 -*-
"""ia_me_app_03062025_1812.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_dEz_dkFC6fA_Ybg0HoEmGdDFBTJYXAv
"""

# Import des librairies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
import re
import nltk
import string
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from textblob import TextBlob

# Télécharger stopwords et autres ressources NLTK si besoin
nltk.download('stopwords')
nltk.download('punkt')

# Chargement des données (ici on suppose que le fichier csv est uploadé dans Colab)
df = pd.read_csv('ia-me/suivi_activites.csv', sep=',', encoding='utf-8', quotechar='"')

# Apercu
print(df.columns)
print(df.head())
print(df.info())

# Conversion des données de la colonne Date en type date
df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d', errors='coerce')

# Traitement des valeurs manquantes (voir nombre)
print(df.isnull().sum())

# Vérification des doublons
print(df.duplicated().sum())

# Nettoyage basique du texte (feedback)
def clean_text(text):
    if pd.isnull(text):
        return ""
    # Mise en minuscule
    text = text.lower()
    # Suppression ponctuation
    text = text.translate(str.maketrans('', '', string.punctuation))
    # Suppression chiffres
    text = re.sub(r'\d+', '', text)
    # Définir les stopwords en français ou anglais selon votre jeu de données
    stop_words = set(stopwords.words('french'))
    # Suppression des stopwords
    text = ' '.join([mot for mot in text.split() if mot not in stop_words])
    return text

df['feedback_clean'] = df['feedback'].apply(clean_text)

# Vérification si le traitement s'est bien déroulé et que la colonne traitée n'est pas vide
print(df['feedback_clean'].head())

"""À ce stade :
*   La colonne Date est bien formatée
*   Les doublons sont supprimés
*   Élément de liste
*   Les Feedback sont nettoyés et une nouvelle colonne Feedback_clean est créée
*   Les champs manquants sont visibles pour traitement ultérieurÉlément de liste


"""

# ANALYSE EXPLORATOIRE DE BASE (EDA)

# Aperçu des statistiques descriptives des colonnes numériques
print("Résumé statistique des colonnes numériques :")
print(df.describe())  # Affiche count, mean, std, min, 25%, 50%, 75%, max pour les colonnes numériques

# Nombre de valeurs uniques par colonne
print("\nNombre de valeurs uniques par colonne :")
print(df.nunique())  # Permet d'identifier les variables catégorielles ou constantes

# Aperçu rapide des types de données
print("\nTypes de données dans le DataFrame :")
print(df.dtypes)  # Vérifie les types (object, int64, float64, etc.)

# Vérification de la présence de valeurs manquantes
print("\nNombre de valeurs manquantes par colonne :")
print(df.isnull().sum())  # Pour détecter les colonnes incomplètes ou problématiques

# Check if there are any non-empty strings after cleaning and stopword removal
if df['feedback_clean'].str.strip().eq('').all():
    print("Erreur: Après nettoyage et suppression des mots vides, la colonne 'Feedback_clean' est vide. Impossible de créer un vocabulaire TF-IDF.")
    # Option 1: Print some raw feedback to understand why it's empty
    print("\nExemples de feedback originaux :")
    print(df['feedback'].head())
    # Option 2: You might need to revisit your cleaning steps or data source
else:
    vectorizer = TfidfVectorizer(max_features=20)
    X = vectorizer.fit_transform(df['feedback_clean'])
    tfidf_df = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())

    # Somme des TF-IDF par mot pour voir les plus importants
    tfidf_sum = tfidf_df.sum().sort_values(ascending=False)
    print("Top mots-clés TF-IDF :")
    print(tfidf_sum)

X = vectorizer.fit_transform(df['feedback_clean'])
tfidf_df = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())

# Somme des TF-IDF par mot pour voir les plus importants
tfidf_sum = tfidf_df.sum().sort_values(ascending=False)
print("Top mots-clés TF-IDF :")
print(tfidf_sum)

# Analyse de sentiment avec TextBlob (en français)
# On utilise TextBlob directement ici, qui marche mieux en anglais, mais ça donnera un aperçu
# Pour un vrai traitement en français, on pourrait utiliser d’autres libs (ex: HuggingFace)
def sentiment_polarity(text):
    return TextBlob(text).sentiment.polarity

df['sentiment'] = df['feedback_clean'].apply(sentiment_polarity)

# Catégorisation simple du sentiment
def categorize_sentiment(score):
    if score > 0.1:
        return 'Positif'
    elif score < -0.1:
        return 'Négatif'
    else:
        return 'Neutre'

df['sentiment_cat'] = df['sentiment'].apply(categorize_sentiment)

# Affichage des counts sentiment
print("\nRépartition des sentiments :")
print(df['sentiment_cat'].value_counts())

# Nuage de mots pour feedback global
all_text = ' '.join(df['feedback_clean'])
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(all_text)

plt.figure(figsize=(12,6))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title("Nuage de mots - Feedback\n \n")
plt.show()

# Graphique des sentiments par type d'activité
plt.figure(figsize=(10,6))
sns.countplot(data=df, x='type_activite', hue='sentiment_cat')
plt.title("Sentiments par Type d'Activité \n")
plt.xticks(rotation=45)
plt.show()

# Moyenne de sentiment par localisation
sentiment_localisation = df.groupby('localisation')['sentiment'].mean().sort_values()

plt.figure(figsize=(8,5))
sentiment_localisation.plot(kind='bar', color='skyblue')
plt.title("Moyenne du sentiment par localisation \n")
plt.ylabel("Score moyen de sentiment \n")
plt.show()

# Croisement nombre participants vs sentiment (boxplot)
plt.figure(figsize=(8,5))
sns.boxplot(data=df, x='sentiment_cat', y='nombre_participants')
plt.title("Nombre de participants selon sentiment \n")
plt.show()

from transformers import pipeline
from tqdm import tqdm

# Nettoyage des feedbacks
df = df.dropna(subset=['feedback'])  # Retirer les lignes sans feedback
feedbacks = df['feedback'].astype(str).tolist()
# Pipeline de sentiment en français
sentiment_model = pipeline("sentiment-analysis", model="tblard/tf-allocine")

# Appliquer le modèle aux feedbacks (limité ici à 100 pour éviter les quotas)
df['sentiment'] = df['feedback'].apply(lambda x: sentiment_model(x[:512])[0]['label'])

# Traitement par batchs
batch_size = 2
sentiments = []

for i in tqdm(range(0, len(feedbacks), batch_size)):
    batch = feedbacks[i:i+batch_size]
    # Tronquer les textes trop longs (optionnel)
    batch = [text[:512] for text in batch]
    results = sentiment_model(batch)
    sentiments.extend([res['label'] for res in results])

# Ajouter la colonne au DataFrame
df = df.reset_index(drop=True)
df['sentiment'] = sentiments

# Affichage des résultats
print(df[['feedback', 'sentiment']].head(10))

### Analyse temporelle des sentiments

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

# S'assurer que la date est bien en datetime
df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d', errors='coerce')

# Nettoyage des labels sentiments (juste au cas où)
#df['sentiment'] = df['sentiment'].astype(str).str.upper().str.strip()
# Convertir en float si ce n’est pas déjà fait
df['sentiment'] = df['sentiment'].astype(float)

# Créer une nouvelle colonne avec labels
def classer_sentiment(score):
    if score > 0.1:
        return 'POS'
    elif score < -0.1:
        return 'NEG'
    else:
        return 'NEU'  # si tu veux ignorer les neutres, tu peux les exclure ensuite

df['sentiment_label'] = df['sentiment'].apply(classer_sentiment)

# Créer une copie filtrée pour analyse
df_filtered = df[df['sentiment_label'].isin(['POS', 'NEG'])].copy()

# Créer colonne mois-année
df_filtered['mois_annee'] = df_filtered['date'].dt.to_period('M').astype(str)

# Agrégation des feedbacks par mois et sentiment
sentiment_par_mois = df_filtered.groupby(['mois_annee', 'sentiment_label']).size().unstack(fill_value=0)

# Convertir l'index en entier pour les régressions
mois_index = np.arange(len(sentiment_par_mois)).reshape(-1, 1)

sentiment_par_mois = sentiment_par_mois.astype(int)

# Tracer le graphique avec lignes de tendance
plt.figure(figsize=(12, 6))

sentiment_par_mois.plot(
    kind='bar',
    color={'POS': '#66bb6a', 'NEG': '#ef5350'},
    edgecolor='black',
    width=0.75,
    ax=plt.gca()
)

# Ajout des courbes de tendance
for sentiment in ['POS', 'NEG']:
    y = sentiment_par_mois[sentiment].values
    model = LinearRegression().fit(mois_index, y)
    trend = model.predict(mois_index)
    plt.plot(sentiment_par_mois.index, trend, linestyle='--', linewidth=2, label=f"Tendance {sentiment}")

# Finalisation
plt.title("Évolution des sentiments par mois avec tendance \n")
plt.xlabel("Mois-Année")
plt.ylabel("Nombre de feedbacks")
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.legend(title="Légende")
plt.tight_layout()
plt.show()

# === Génération d'un commentaire automatique ===
last = sentiment_par_mois.iloc[-1]
first = sentiment_par_mois.iloc[0]

evolution_pos = last['POS'] - first['POS']
evolution_neg = last['NEG'] - first['NEG']

commentaire = "🔎 **Analyse automatique :**\n"

if evolution_pos > 0:
    commentaire += f"- Les feedbacks **positifs ont augmenté** de {evolution_pos} entre {sentiment_par_mois.index[0]} et {sentiment_par_mois.index[-1]}.\n"
elif evolution_pos < 0:
    commentaire += f"- Les feedbacks **positifs ont diminué** de {-evolution_pos} sur la même période.\n"
else:
    commentaire += "- Les feedbacks **positifs sont restés stables**.\n"

if evolution_neg > 0:
    commentaire += f"- Les feedbacks **négatifs ont augmenté** de {evolution_neg}.\n"
elif evolution_neg < 0:
    commentaire += f"- Les feedbacks **négatifs ont diminué** de {-evolution_neg}.\n"
else:
    commentaire += "- Les feedbacks **négatifs sont restés stables**.\n"

print(commentaire)
#

### Clustering thematique des feedbacks
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.manifold import TSNE

# Vectorisation TF-IDF
vectorizer = TfidfVectorizer(max_features=1000, max_df=0.8, min_df=5)
X = vectorizer.fit_transform(df['feedback_clean'])

# Clustering avec KMeans
n_clusters = 5
kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
kmeans.fit(X)

df['cluster'] = kmeans.labels_

# Affichage des mots-clés par cluster
terms = vectorizer.get_feature_names_out()
order_centroids = kmeans.cluster_centers_.argsort()[:, ::-1]

print("🧾 Mots-clés principaux par cluster :\n")
for i in range(n_clusters):
    print(f"Cluster {i} :")
    print(", ".join([terms[ind] for ind in order_centroids[i, :10]]))
    print()

# Visualisation 2D avec t-SNE
tsne = TSNE(n_components=2, random_state=42)
X_embedded = tsne.fit_transform(X.toarray())

plt.figure(figsize=(10, 8))
sns.scatterplot(x=X_embedded[:, 0], y=X_embedded[:, 1], hue=df['cluster'], palette='viridis', s=50)
plt.title("Projection 2D des feedbacks par cluster \n")
plt.xlabel("-- 1 --")
plt.ylabel("-- 2 --")
plt.legend(title="Cluster")
plt.show()

"""✅ Cluster 0 : Exploration / Mobilisation communautaire

Mots-clés : près, amener, rencontrer, rejoindre, ouvrir
➡️ Interprétation : Ce cluster semble lié aux actions de terrain, au contact avec les communautés, à l’engagement ou mobilisation locale.

Étiquette proposée : Mobilisation communautaire et terrain
✅ Cluster 1 : Organisation / Logistique d’évènements

Mots-clés : nouveau, forêt, rencontre, chemise, grave
➡️ Interprétation : Mélange d’éléments logistiques et d’expériences nouvelles ou imprévues, peut suggérer des activités sur le terrain ou en milieu rural, avec des aléas logistiques.

Étiquette proposée : Déploiement logistique et imprévus
✅ Cluster 2 : Réactions personnelles / Critiques ou doutes

Mots-clés : inutile, conscience, réponse, battre
➡️ Interprétation : Feedbacks exprimant du doute, un sentiment d’inutilité ou de conflit, peut-être liés à une insatisfaction ou incompréhension.

Étiquette proposée : Retours critiques ou insatisfaction
✅ Cluster 3 : Sentiments / Ressenti émotionnel

Mots-clés : rêve, fatigue, naissance, inquiétude
➡️ Interprétation : Retour à dimension plus subjective, émotionnelle, liée à des sentiments profonds ou à un effort intense, voire épuisement.

Étiquette proposée : Fatigue et émotions personnelles
✅ Cluster 4 : Perception positive / Appréciation

Mots-clés : plaisir, idée, impression, regarder, choisir
➡️ Interprétation : Feedbacks plutôt positifs, avec des mots valorisant l’expérience, l’intérêt ou la clarté des actions menées.

Étiquette proposée : Perception positive et satisfaction
"""

